GTEST_DIR = ../submodules/googletest/googletest
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h $(GTEST_DIR)/include/gtest/internal/*.h
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)
BUILD_DIR ?= .

CPPFLAGS += -isystem $(GTEST_DIR)/include -I$(GTEST_DIR)
CXXFLAGS += -g -Wall -Wextra -Wno-missing-field-initializers -pthread

$(BUILD_DIR)/gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $(GTEST_DIR)/src/gtest-all.cc

$(BUILD_DIR)/gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $(GTEST_DIR)/src/gtest_main.cc

$(BUILD_DIR)/gtest.a : $(BUILD_DIR)/gtest-all.o
$(BUILD_DIR)/gtest_main.a : $(BUILD_DIR)/gtest-all.o $(BUILD_DIR)/gtest_main.o

ARFLAGS += -c
$(BUILD_DIR)/%.a :
	@$(AR) $(ARFLAGS) $@ $^ > /dev/null

gtest.a: $(BUILD_DIR)/gtest.a
gtest_main.a: $(BUILD_DIR)/gtest_main.a

